apiVersion: v1                         # API version for Service resources
kind: Service                          # Resource type: Service
metadata:
  name: {{ .Release.Name }}-service                # Name of the service
spec:
  type: NodePort                       # Service type: makes service accessible on a port on each node
  selector:
    app: {{ .Values.labels.app }}                   # Selects pods with this label to send traffic to
  ports:
    - port: {{ .Values.ports.port }}                       # Port the service exposes
      targetPort: {{ .Values.ports.targetport }}                 # Port on the pod that traffic is sent to
      nodePort: {{ .Values.ports.nodeport }}                  # Port on each node where service is accessible (30000-32767)
