apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-reach-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: surendra1302/python-reach-backend:v1
